### ISSUE TITLE
Feature request: world-coordinate particles

### ISSUE THREAD

**Issue by jfbilodeau** [korlibs/korge-next#341]
It would be really nice to have particles that use the position of the world (or parent) instead of their container. This would lead to more natural motion when a particle emitter is moved.

**Comment by soywiz** [comment]
Here it is typically achieved by having an empty or invisible view in your space, and then synchonizing globalPosition with a particle system in the global space. Alternatively we could create a container node with an inverted global matrix to revert the current transformation so it is generic and could be reused by other views.

do you know an engine that already do what you propose?

**Comment by jfbilodeau** [comment]
Godot comes to mind: https://docs.godotengine.org/en/stable/tutorials/2d/particle_systems_2d.html#local-coords

Implementing that would be really appreciated!

**Comment by soywiz** [comment]
Oh I see. Maybe instead of changing X and Y from the view, you want to change the emitterPos: https://github.com/korlibs/korge-next/blob/master/korge/src/commonMain/kotlin/com/soywiz/korge/particle/ParticleEmitterView.kt#L40

But maybe we can provide a boolean so the x and y changes the emitter pos instead of the x and y positions of the view

**Comment by jfbilodeau** [comment]
A boolean flag would be perfect!
